# Generated by Django 3.2.8 on 2021-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, max_length=15, verbose_name='Created DateTime'),
        ),
    ]
